name: imgrep
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  photo_manager_image_provider: ^2.2.0
  shared_preferences:
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  path: ^1.9.1
  photo_manager: ^3.7.1
  geocoding: ^2.1.0
  intl: ^0.20.2
  sqflite: ^2.4.2
  onnxruntime: ^1.4.1
  path_provider: ^2.1.5
  flutter_foreground_task: ^9.1.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

